service:
  name: todo

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  # bucket: bucket-name

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x

functions: 
  postTodo:
    handler: src/functions/postTodo.handle
    events:
      - http:
          path: /todo/{userid}
          method: POST
          cors: true
  getTodo:
    handler: src/functions/getTodo.handle
    events:
      - http:
          path: /todo/{userid}
          method: GET
          cors: true


resources:
  Resources:
    dbTodoList:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todo_list
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userid
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH